"""Generic mixed-language Cadence Genus input preparation.

This module consumes resolved WOLF source metadata only.  It deliberately has
no knowledge of ESP, FABulous, or any generator-specific conventions.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
import hashlib
from pathlib import Path
import shutil
import subprocess
from typing import Any, Mapping, Optional

import yaml

from wolf.context import ResolvedContext


@dataclass(frozen=True)
class GenusValidation:
    name: str
    available: bool
    detail: str


@dataclass(frozen=True)
class GenusInputs:
    directory: Path
    source_script: Path
    run_script: Path
    manifest: Path


def _normalize_vhdl_standard(value: Any) -> str:
    canonical = str(value or "93")
    normalized = {"87": "1987", "1987": "1987", "93": "1993", "1993": "1993",
                  "08": "2008", "2008": "2008"}.get(canonical)
    if normalized is None:
        raise ValueError(
            f"unsupported VHDL standard {canonical!r}; supported values are 1987, 1993, and 2008"
        )
    return normalized


def allocate_genus_run(context: ResolvedContext, *, clean: bool = False) -> Path:
    """Allocate a new numbered run without modifying earlier runs."""
    base = context.workspace_root / context.design_name / f"{context.design_name}.{context.process}"
    if not clean and not context.run_directory.exists():
        return context.run_directory
    index = 1
    while (base / f"{context.design_name}.{index}").exists():
        index += 1
    return base / f"{context.design_name}.{index}"


def _period_ns(period_ps: Any) -> str:
    value = Decimal(str(period_ps)) / Decimal("1000")
    return format(value.normalize(), "f").rstrip("0").rstrip(".") or "0"


def validate_genus(
    context: ResolvedContext,
    *,
    executable_lookup=shutil.which,
) -> tuple[GenusValidation, ...]:
    """Validate Genus and any explicitly configured technology inputs.

    Technology-independent elaboration may omit physical views.  When a view
    is configured, however, it must exist before a run is allocated.
    """
    checks = []
    genus = executable_lookup("genus")
    checks.append(GenusValidation("genus", genus is not None, genus or "unavailable"))
    for key in ("LIBRARY_FILES", "LEF_FILES", "QRC_TECH_FILE", "TECHNOLOGY_SETUP"):
        value = context.values.get(key)
        if value:
            paths = [Path(item) for item in value.split()]
            missing = [str(path) for path in paths if not path.is_file()]
            checks.append(GenusValidation(key, not missing, ", ".join(missing) or value))
    return tuple(checks)


def _tcl_quote(value: str) -> str:
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""


def _digest(files: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.read_bytes())
    return digest.hexdigest()


def prepare_genus_inputs(context: ResolvedContext, destination: Path) -> GenusInputs:
    """Write deterministic Genus scripts and a provenance manifest."""
    if not context.sources:
        raise ValueError("Cadence Genus preparation requires ordered resolved sources")
    if not context.design_top:
        raise ValueError("Cadence Genus preparation requires design.top")
    genus_vhdl_standard = _normalize_vhdl_standard(context.vhdl_standard)
    destination = destination.resolve()
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "reports").mkdir(exist_ok=True)
    (destination / "outputs").mkdir(exist_ok=True)
    source_script = destination / "sources.tcl"
    run_script = destination / "run.tcl"
    manifest = destination / "genus-inputs.yaml"
    constraints = destination / "constraints.sdc"

    lines = [
        "# Generated by WOLF; source order is part of the resolved context.",
        f"set_db hdl_vhdl_read_version {genus_vhdl_standard}",
    ]
    if context.include_directories:
        include_values = " ".join(_tcl_quote(str(path)) for path in context.include_directories)
        lines.append(f"set_db hdl_search_path {{{include_values}}}")
    if context.defines:
        defines = " ".join(_tcl_quote(value) for value in context.defines)
        lines.append(f"set_db hdl_verilog_define {{{defines}}}")
    for source in context.sources:
        language = "-vhdl" if source.language == "vhdl" else "-sv"
        lines.append(f"read_hdl {language} -library {source.library} {_tcl_quote(str(source.path))}")
    source_script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    constraints.write_text("\n".join(
        f"create_clock -name {clock.name} -period {_period_ns(clock.period_ps)} [get_ports {clock.port}]"
        for clock in context.clocks
    ) + ("\n" if context.clocks else ""), encoding="utf-8")

    run_script.write_text(
        "# Generated by WOLF; execution is intentionally separate from preparation.\n"
        "# Every operation is inside one catch so Genus cannot mask a Tcl error.\n"
        "if {[catch {\n"
        f"    source {_tcl_quote(str(source_script))}\n"
        f"    elaborate {context.design_top}\n"
        f"    read_sdc {_tcl_quote(str(constraints))}\n"
        "    check_design -unresolved\n"
        "    report_hierarchy > reports/hierarchy.rpt\n"
        "    report_messages > reports/messages.rpt\n"
        "} error options]} {\n"
        "    puts stderr \"WOLF Genus failure: $error\"\n"
        "    if {[dict exists $options -errorinfo]} { puts stderr [dict get $options -errorinfo] }\n"
        "    if {[dict exists $options -errorcode]} { puts stderr \"ErrorCode: [dict get $options -errorcode]\" }\n"
        "    exit 1\n"
        "}\n"
        "exit 0\n",
        encoding="utf-8",
    )
    records = [
        {
            "path": str(source.path), "order": source.order, "language": source.language,
            "library": source.library, "role": source.role,
            **({"sha256": source.checksum} if source.checksum else {}),
        }
        for source in context.sources
    ]
    data: Mapping[str, Any] = {
        "schema": "wolf.cadence-genus-inputs/v1",
        "design": {"name": context.design_name, "top": context.design_top},
        "vhdl_standard": context.vhdl_standard or "93",
        "sources": records,
        "include_directories": [str(path) for path in context.include_directories],
        "defines": list(context.defines),
        "constraints": {"clocks": [
            {"name": clock.name, "port": clock.port, "period_ps": clock.period_ps}
            for clock in context.clocks
        ]},
        "outputs": {
            "reports": str(destination / "reports"),
            "netlist": str(destination / "outputs" / f"{context.design_name}.v"),
            "constraints": str(constraints),
        },
        "packages": [
            {"id": identifier, "revision": revision}
            for identifier, revision in sorted(context.package_revisions.items())
        ],
        "source_checksum": _digest([source.path for source in context.sources]),
    }
    manifest.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return GenusInputs(destination, source_script, run_script, manifest)


def validate_genus_or_raise(context: ResolvedContext) -> str:
    checks = validate_genus(context)
    failures = [f"{item.name}: {item.detail}" for item in checks if not item.available]
    if failures:
        raise ValueError("Cadence Genus validation failed: " + "; ".join(failures))
    return next(item.detail for item in checks if item.name == "genus")


def run_genus(context: ResolvedContext, *, clean: bool = False) -> tuple[int, Path]:
    """Allocate, prepare, freeze provenance, and execute one Genus run."""
    genus = validate_genus_or_raise(context)
    run_directory = allocate_genus_run(context, clean=clean)
    inputs = prepare_genus_inputs(context, run_directory / "backend" / "cadence-genus")
    resolved = yaml.safe_load(inputs.manifest.read_text(encoding="utf-8"))
    resolved["schema"] = "wolf.resolved-run/v1"
    resolved["execution"] = {
        "executor": "native", "tool": "genus", "executable": genus,
        "working_directory": str(inputs.directory),
        "command": [genus, "-files", "run.tcl", "-log", "genus.log"],
    }
    resolved["environment"] = context.environment_name
    resolved["workspace"] = {
        "root": str(context.workspace_root), "run_directory": str(run_directory),
    }
    resolved_source = inputs.directory / "resolved.yaml"
    resolved_source.write_text(yaml.safe_dump(resolved, sort_keys=False), encoding="utf-8")
    from wolf.provenance import freeze_run_manifest
    freeze_run_manifest(
        resolved_source, run_directory,
        generated_directory=inputs.directory,
        generated_files={
            "genus_sources": str(inputs.source_script),
            "genus_constraints": str(inputs.directory / "constraints.sdc"),
            "genus_script": str(inputs.run_script),
        },
    )
    result = subprocess.run(
        [genus, "-files", "run.tcl", "-log", "genus.log"],
        cwd=inputs.directory, check=False,
    )
    return result.returncode, run_directory
